name: 'Get the next version code'
description: 'An action to know the next version code of an app in google play console'
branding:
  icon: 'play'
  color: 'green'
inputs:
  serviceAccountJsonFile:
    description: "The json file of the service account private key to authorize access to google play console api data"
    required: true
  packageName:
    description: "The package name, of the app"
    required: true
outputs:
  nextVersionCode:
    description: 'The next version code'
runs:
  using: 'node20'
  main: 'lib/index.js'
